### ISSUE TITLE
url generation with invlad urls

### ISSUE THREAD

**Issue by ploughnane** [CycloneDX/cyclonedx-node-module#107]
When generating a bom with this repo I have found that the component, externalReferences, reference type of vcs will produce an invalid url which will start with "git+" as shown below
```
<externalReferences>
 <reference type="website">
  <url>https://material-ui.com/</url>
 </reference>
 <reference type="issue-tracker">
  <url>https://github.com/mui-org/material-ui/issues</url>
 </reference>
 <reference type="vcs">
  <url>git+https://github.com/mui-org/material-ui.git</url>
 </reference>
</externalReferences>
```

When trying to reenter a bom generated with the incorrect url, the vcs reference type will drop. In my case the vcs is similar enough to the other two references that this is no impact. 

Using CyloneDX Node.js module 2.0.2 with node version 14.4.0

**Comment by jkowalleck** [comment]
you were generating the output in XML format, i see. the `externalReference.url` needs to be `xml::anyURI` compliant.  "git+https://github.com/mui-org/material-ui.git" complies to `xml::anyURI`. 
**Therefore i will close this very issue.**

_Attention_: we are speaking of URI according to CyconeDX xml spec - not URL. Dont get this confused.

If you feel the issue waas not closed, feel free to open another one and shed some light o the problem:
* how were you generating the XML?
* what makes you think the URL is invalid?
