### ISSUE TITLE
Set MetaData Component from Outside

### ISSUE THREAD

**Issue by patspaeth** [CycloneDX/cyclonedx-node-module#113]
It would be helpful when I can set the name and version of the metaData component from outside.

**Comment by coderpatros** [comment]
Hi @patspaeth 

This is definitely something that should be easy to do. But it will most like be implemented in the CLI tool first so all users can benefit.

**Comment by davideicardi** [comment]
@coderpatros What do you mean "in the CLI tool"? Which CLI tool?

I would expect to implement these features inside each CycloneDx generator. Or there is another CLI tool?

**Comment by coderpatros** [comment]
@davideicardi, yeah the cyclonedx-cli tool https://github.com/CycloneDX/cyclonedx-cli/

I'm not against adding it here if someone wants to contribute the feature. Just I don't want to have to implement it myself across multiple implementations.
