### ISSUE TITLE
Cannot generate BOM file

### ISSUE THREAD

**Issue by midav7** [CycloneDX/cyclonedx-node-module#118]
Hi there! Can someone explain to me why do I need to run npm install before I generate BOM file for project dependencies?
It seems for me that I miss something. I run this from the project directory where _package.json_ file locating:
<img width="1224" alt="Screen Shot 2021-04-13 at 14 49 49" src="https://user-images.githubusercontent.com/40424976/114548031-e0ae0e80-9c67-11eb-9fee-e767e35704c0.png">
I appreciate any advice. Thank you in advance.

**Comment by coderpatros** [comment]
`read-installed` is used to retrieve information about the packages that are installed

**Comment by midav7** [comment]
Could you please expand on this? Is this a CLI argument for `cyclonedx-bom` ? I'm basically trying  generate BOM file having a project cloned on my filesystem.

**Comment by coderpatros** [comment]
Information is read from the files installed into node_modules. So you need to run `npm install` first.

Or do you not know what is meant by `npm install`?

**Comment by ddurham2** [comment]
Same issue here.  I've run npm install ,and ./node_modules is full of packages.  I'm also running cyclonedx-bom with -d to include dev packages, but I'm getting the same error w/ or w/o that arg.

**Comment by jkowalleck** [comment]
all questions answered.
input from @ddurham2  will be considered.
