### ISSUE TITLE
Detected dependencies diff with cdxgen output

### ISSUE THREAD

**Issue by F242MX** [CycloneDX/cyclonedx-node-module#120]
I have observed some differences in the output (bom.xml) of cyclonedx-bom compared to the output of cdxgen.

In some projects cyclonedx-bom reports less dependencies than cdxgen, and on rare occurences 2 or 3 more (but they mostly are the project itself).

For example, I have a project in which cyclonedx-bom only detects 5 dependencies, when cdxgen reports 63 dependencies.

Do you have a clue on what is going on?

**Comment by stevespringett** [comment]
The node module does not include dev dependencies by default. Try adding `--include-dev` and see if there are differences.

**Comment by F242MX** [comment]
Yes there is a difference :)
Actually cyclonedx-bom now reports a few more dependencies than cdxgen does.
