### ISSUE TITLE
Upgrade xmldom to version 0.5.0 or higher

### ISSUE THREAD

**Issue by dmartingomez** [CycloneDX/cyclonedx-node-module#130]
As per Low risk vulnerability:
https://snyk.io/vuln/SNYK-JS-XMLDOM-1084960

Many thanks

**Comment by dmartingomez** [comment]
Please approve MR:
https://github.com/CycloneDX/cyclonedx-node-module/pull/119

**Comment by coderpatros** [comment]
Available in v3.0.0
