### ISSUE TITLE
The option to append the bom with option -a does not exist anymore

### ISSUE THREAD

**Issue by verlindb** [CycloneDX/cyclonedx-node-module#138]
Seems like the contract of the cli is broken since 11 hours ago.
We have used option -a to append cyclonedx bom generation in our ci pipelines

**Comment by coderpatros** [comment]
Hi @verlindb, that's correct. Hence the major version bump (as well as us dropping support for Node.js v8).

The recommended solution for this is to use the [CLI tool](https://github.com/CycloneDX/cyclonedx-cli/) merge option. It supports all CycloneDX formats and versions.

We didn't want to continue maintaining that functionality in two places.

**Comment by verlindb** [comment]
Changed outline of the pipeline as described above

command : 
cyclonedx-bom  -o  D:\Builds\GenericAgent1\_work\246\s/FrontEnd/bom.xml
 throw "Unsupported component type. Supported types are " + Component.supportedComponentTypes().toString();


This is now breaking all of our ci/cd pipelines

**Comment by jkowalleck** [comment]
@verlindb is this still an issue?
