### ISSUE TITLE
Unsupported component type. Supported types are " + Component.supportedComponentTypes().toString(); on bom generation

### ISSUE THREAD

**Issue by verlindb** [CycloneDX/cyclonedx-node-module#139]
Changed outline of the pipeline as described above

command :
cyclonedx-bom -o D:\Builds\GenericAgent1_work\246\s/FrontEnd/bom.xml
throw "Unsupported component type. Supported types are " + Component.supportedComponentTypes().toString();

This is now breaking all of our ci/cd pipelines

**Comment by coderpatros** [comment]
Oof, that's a bad one. Fix incoming.

**Comment by verlindb** [comment]
For now only option is to set npm install of cyclonedx-bom to fixed version 2.0.2
due to breaking changes

**Comment by coderpatros** [comment]
v3.0.1 has a temporary fix for this. Looks like commander, one of our dependencies, isn't setting the default values anymore for command line options. So I'm going to leave this issue open until the underlying issue is resolved.

**Comment by coderpatros** [comment]
Fully resolved in v3.0.2
