### ISSUE TITLE
--include-dev not working

### ISSUE THREAD

**Issue by oz-viadee** [CycloneDX/cyclonedx-node-module#143]
The option to include dev dependencies is not correctly passed to the `read-installed` package. Because of this, `--include-dev` does nothing.

This line should be changed:
https://github.com/CycloneDX/cyclonedx-node-module/blob/5bf10df54ce956880c33826f5b7184def335ff64/bin/cyclonedx-bom#L61
to:
`readInstalledOptions.dev = options.includeDev; `

**Comment by coderpatros** [comment]
Available in v3.0.3, thanks @oz-viadee
