### ISSUE TITLE
Help with Dependency graph

### ISSUE THREAD

**Issue by dbrighton** [CycloneDX/cyclonedx-node-module#145]
I have started using CycloneDX for our  node.js (angular) project and our .Net Core 3.1  Rest API.  It works great however we never see a Dependency graph ("<dependencies> nodes") in our generated BOM reports. What do I need to get this information added to the BOM file?

**Comment by stevespringett** [comment]
Dependency graphs are not yet supported in the node module. But it's being tracked in #61 so support for it will be coming soon.

**Comment by dbrighton** [comment]
What about for the DotNet version?

**Comment by stevespringett** [comment]
Dependency graph support for the .NET version is being tracked in https://github.com/CycloneDX/cyclonedx-dotnet/issues/138

**Comment by jkowalleck** [comment]
closed as question was answered.
