### ISSUE TITLE
Retrieve hashes from `package-lock.json`

### ISSUE THREAD

**Issue by sophiewigmore** [CycloneDX/cyclonedx-node-module#161]
In NPM 7 (used in node engine v14+), there is a new `package-lock.json` structure (lockfile version 2). This structure removes all module integrity information from the module specific `package.json` files, and moves it into the top-level `package-lock.json`. It appears that this tool only looks in the old location, and does not consider the `integrity` that may be in the `package-lock.json`. Because of this, the cyclonedx-node-module tool does not find any hashes for node modules in apps that use node-engine v14+. Ideally, I would still expect hashes to be located for these apps.

I mentioned this issue in #25, but I think this issue can be resolved by expanding the files that are looked at in [HashList.js](https://github.com/CycloneDX/cyclonedx-node-module/blob/master/model/HashList.js) to include the lockfile.

**Comment by stevespringett** [comment]
@sophiewigmore Do you know how the hash values are calculated for npm packages?

Ideally, we would want to calculate the integrity for all or most the supported hash algorithms, not just SHA-256 or 384, whatever npm uses.

**Comment by sophiewigmore** [comment]
@stevespringett Hi 👋 

NPM provides the values as `sha512` or `sha1` [subresource integrity](https://w3c.github.io/webappsec-subresource-integrity/). 

I understand that CycloneDX supports a whole array of supported hash algorithms, but what's the reason for converting hash algorithms that are natively provided by the language? Especially since both of `sha1` and `sha512` are supported algorithms.

To me, this seems like two separate issues. My issue is that I want the same functionality that currently exists for retrieving hashes to work for all node versions, by looking at the `package-lock.json` when necessary. If I understand correctly, the issue in #25 is around supporting the full set of supported algorithms. In my eyes, each one of these could be solved separately. Is that a reasonable conclusion, or am I missing something about how this works?

**Comment by stevespringett** [comment]
Short term, yes, we can get this module to support all node versions. Long term however, we want to support as many hash algs as possible for every component. One of many reasons has to do with conversions. When converting CycloneDX to another format (SPDX for example), SHA1 is actually a requirement. If a SHA512 is the only alg available for a component, then the that data will be lost in conversion whereas if the CycloneDX SBOM had both, it could be convered.

How would you suggest fixing the node module in the short term to support Node v14+?

I'm assuming changes would need to be made at:
https://github.com/CycloneDX/cyclonedx-node-module/blob/master/model/HashList.js#L43

**Comment by sophiewigmore** [comment]
I see, that makes sense. Thank you for the context, I hadn't thought about the conversion needs

I am working on a Pull Request for the short term fix as we speak. It will definitely include changes to [HashList](https://github.com/CycloneDX/cyclonedx-node-module/blob/master/model/HashList.js#L43). I will link to that PR when it's open!

**Comment by stevespringett** [comment]
v3.0.5 has been released which includes this new functionality. Thanks for the input and for providing the necessary pull request. Much appreciated.
