### ISSUE TITLE
3.0.5 regression. Fails on not finding package-lock.json

### ISSUE THREAD

**Issue by relnah** [CycloneDX/cyclonedx-node-module#166]
When running 3.0.5 with npx after building with yarn we get this crash. Running exact same in 3.0.4 works.

internal/fs/utils.js:220
    throw err;
    ^

Error: ENOENT: no such file or directory, open 'package-lock.json'
[90m    at Object.openSync (fs.js:440:3)[39m
[90m    at Object.readFileSync (fs.js:342:35)[39m
    at /root/.npm/_npx/1/lib/node_modules/[4m@cyclonedx[24m/bom/index.js:26:34
    at /root/.npm/_npx/1/lib/node_modules/[4m@cyclonedx[24m/bom/node_modules/[4mread-installed[24m/read-installed.js:142:5
    at /root/.npm/_npx/1/lib/node_modules/[4m@cyclonedx[24m/bom/node_modules/[4mread-installed[24m/read-installed.js:263:14
    at cb (/root/.npm/_npx/1/lib/node_modules/[4m@cyclonedx[24m/bom/node_modules/[4mslide[24m/lib/async-map.js:47:24)
    at /root/.npm/_npx/1/lib/node_modules/[4m@cyclonedx[24m/bom/node_modules/[4mread-installed[24m/read-installed.js:263:14
    at cb (/root/.npm/_npx/1/lib/node_modules/[4m@cyclonedx[24m/bom/node_modules/[4mslide[24m/lib/async-map.js:47:24)
    at /root/.npm/_npx/1/lib/node_modules/[4m@cyclonedx[24m/bom/node_modules/[4mread-installed[24m/read-installed.js:263:14
    at cb (/root/.npm/_npx/1/lib/node_modules/[4m@cyclonedx[24m/bom/node_modules/[4mslide[24m/lib/async-map.js:47:24) {
  errno: [33m-2[39m,
  syscall: [32m'open'[39m,
  code: [32m'ENOENT'[39m,
  path: [32m'package-lock.json'[39m

**Comment by sophiewigmore** [comment]
I am looking into this issue now
