### ISSUE TITLE
Silently fails to write SBOM if target directory for output does not exist

### ISSUE THREAD

**Issue by obfischer** [CycloneDX/cyclonedx-node-module#168]
Version 3.0.3 (or 3.0.4) silently fails to write the SBOM files, if it should write its output to a non-existing directory, e.g. `cyclonedx-bom -o target/bom.xml`. Instead of failing, it should either create the missing directory/ies or fail with an descriptive error message.

**Comment by jkowalleck** [comment]
i'd recommend to fail with a non-zero exit code.
creating the missing directories might cause unexpected side-effects on the target system.
