### ISSUE TITLE
Libraries with no vulnerabilities coming through

### ISSUE THREAD

**Issue by mandibles23** [CycloneDX/cyclonedx-node-module#176]
Since the last update on 9/13 we are seeing boms without vulns coming through. Also no license. Anyone else seeing this?

**Comment by stevespringett** [comment]
The CycloneDX does not query for, or include vulnerability information in the BOM.

If you're not seeing license info, can you provide a project that this can be reproduced on?

**Comment by mandibles23** [comment]
Hi Steve, I wasn't clear my apologies. We are seeing a few scans where there is no sha hash inside the bom (seeing this for a few lodash builds and others too). I'm not sure when the issue started now. Do you have an insight on this behavior? Thank you so much for reaching out

**Comment by stevespringett** [comment]
I have not noticed any odd behavior. Do you have a sample repo that I can reproduce this on?

**Comment by mandibles23** [comment]
I'm checking which ones I can share, would it be enough to send the boms/package.json? Thanks!

**Comment by jkowalleck** [comment]
can this one be closed?

**Comment by mandibles23** [comment]
Yes, thank you!


Sent from Yahoo Mail for iPhone


On Monday, December 6, 2021, 4:06 AM, Jan Kowalleck ***@***.***> wrote:




can this one be closed?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
