### ISSUE TITLE
Cli clash with cyclonedx-python

### ISSUE THREAD

**Issue by Anthony-Mckale** [CycloneDX/cyclonedx-node-module#193]
cyclone dx python uses "cyclonedx-bom" and "cyclonedx-py"
https://github.com/CycloneDX/cyclonedx-python/blob/master/pyproject.toml

unfortunately cyclonedx-node uses "cyclonedx-bom" as well

so when cyclonedx commands are both installed, and the node path is below the python module path

you can't run cyclonedx-node-module

suggesting we have cyclconedx-node use "cyclonedx-bom" and "cyclonedx-node" (like python version), so the "cyclonedx-node" can be used in cases that multiple tools are installed

**Comment by jkowalleck** [comment]
thank you very much.
the fix was applied, available since `3.2.0`
