### ISSUE TITLE
add coding standards via "standard"

### ISSUE THREAD

**Issue by Anthony-Mckale** [CycloneDX/cyclonedx-node-module#194]
Look good sir/madam,

While i was creating a feature pull request for the multi cli issue, spotted the coding standards were a little old fashioned

thought i'd add a branch using standard, which is what i'm using for my modern node project, find it really helps clean up the code nicely, especially with it's easy to use ```standard --fix``` flag

spots alot of issues and unused code, as well as making the ocde look nice and clean

https://standardjs.com/

**Comment by Anthony-Mckale** [comment]
committed pull request with standardjs applied

**Comment by jkowalleck** [comment]
coding standards were applied.
