### ISSUE TITLE
Support for repository_url and vcs_url in purl field

### ISSUE THREAD

**Issue by vaaralav** [CycloneDX/cyclonedx-node-module#20]
It would be great if packages that are installed from non-NPM origin had the information in their purl.

For example
```
npm install git+ssh://git@github.com:npm/cli.git#v1.0.27
```
Would create a component with purl `pkg:npm/cli@1.0.27?vcs_url=git+git+ssh://git@github.com:npm/cli.git#v1.0.27`

Similarly `repository_url` could be added for packages installed from custom registries.

**Comment by jkowalleck** [comment]
this feature was implemented in https://github.com/CycloneDX/cyclonedx-node-npm/
please switch to the NPM flavour of this package.
