### ISSUE TITLE
Include cyclonedx-cli in the npm package so that projects can upgrade to v3

### ISSUE THREAD

**Issue by garth** [CycloneDX/cyclonedx-node-module#237]
Since --append was dropped in v3, the current suggestion is to use the cyclonedx-cli instead, but since cyclonedx-cli is only avalable as a manual download it's not suitable for secure build environments.

One option could be to include the cli in the npm package?

**Comment by jkowalleck** [comment]
you are talking about [cyclonedx-cli], right?

@garth could you elaborate your expectations.

what version of [cyclonedx-cli] should be bundled to the node package? always the latest?
ship the binary or the source-code of [cyclonedx-cli]? 
which binary of [cyclonedx-cli] to ship? the win32? the win64? osX? arm? one of the others? all of them? 
how should it be handled if newer versions of [cyclonedx-cli] are released? 

----

> since cyclonedx-cli is only avalable as a manual download it's not suitable for secure build environments.

how is a manual download less "suitable for secure build environments" than a `npm ci`/`nom install`? 
just download the file, use checksums for integrity tests, done.
suggestion: ship the file with your project, have it globally available in your build environment, whatever suites your needs. 

[cyclonedx-cli]: https://github.com/CycloneDX/cyclonedx-cli

**Comment by garth** [comment]
> you are talking about cyclonedx-cli, right?
> as a followup of #189

yes

Since the recommendation is to use cyclonedx-cli, I am looking for ways to make merge accessible in a similar way as it was v2 of this package.

As far as I can see the removal of `--append` is probably the only blocker for projects to move to v3 (for example, pushing a BOM to [dependency track](https://dependencytrack.org/) requires a single file).

> what version of cyclonedx-cli should be bundled to the node package? always the latest?
> ship the binary or the source-code of cyclonedx-cli?
> which binary of cyclonedx-cli to ship? the win32? the win64? osX? arm? one of the others? all of them?
> how should it be handled if newer versions of cyclonedx-cli are released?

All good questions to which I don't have specific answers, except to say that other npm package have working solutions which could be used a reference. For versioning, it might be an idea to package the cyclonedx-cli separately.

> how is a manual download less "suitable for secure build environments" than a npm ci/nom install?

Secure build environments often don't have direct internet access, they only have access to src and vetted package registries, so direct downloads are not an option.

> ship the binary of cyclonedx-cli with your project

This could be an option, but then we have the same architecture issues as packaging the cli with npm

> have it globally available in your build environment

Also an option, but in our case this comes significant issues (both technical and bureaucratic) unless we could get the cyclonedx-cli to be included in operating system packages managers (eg redhat).

---

For the time being v2 is working fine. I just want to be sure that we don't run into issues later. Looking at the stats, it seems that about 10% are using versions before v3, though it's difficult to know if that's for the same reason.

**Comment by jkowalleck** [comment]
Merging BOMs is not trivial and implementing it multiple times is just impractical. see https://github.com/CycloneDX/cyclonedx-node-module/issues/138#issuecomment-871970625

I totally see your reasons. But please understand: merging multiple BOMs is no longer a feature of the node package since v3.

There are tools for the job, that can be used fr merging/converting BOMs.
Feel free to join the [discussion group](https://groups.io/g/CycloneDX) to get help from others that designed/implemented CI jobs for BOM transformations.
