### ISSUE TITLE
[YARN] Yarn support?

### ISSUE THREAD

**Issue by factoidforrest** [CycloneDX/cyclonedx-node-module#238]
A lot of folks use yarn.  It looks like your current strategy of reading the lockfile will work fine, it just needs to be smart about whether it is reading a package-lock or a yarn.lock file.  Most of the code should work fine though!

**Comment by jkowalleck** [comment]
need to get #215 done first.
then all the [yarn related issues](https://github.com/CycloneDX/cyclonedx-node-module/issues?q=is%3Aissue+is%3Aopen+yarn) can be fixed.

**Comment by jkowalleck** [comment]
was fixed by #/282

**Comment by Ripolin** [comment]
Hi,

For which version of Yarn this feature works ? Because when using on yarn v2 I've got the error ```SyntaxError: Unknown token: { line: 3, col: 2, type: 'INVALID', value: undefined } 3:2 in lockfile```.

**Comment by jkowalleck** [comment]
which version of yarn are you using? output of `yarn -v` 
which versions of `@cyclonedx/bom` were you using? 
which versions of `synp` were you using? 


which packages were you using? output of `yarn list`? 
could you provide a reproducible example? maybe as a pull-request? or as a standalone repository?

please see the reproducible example here: https://github.com/CycloneDX/cyclonedx-node-module/tree/master/tests/integration/with-yarn-lockfile

**Comment by jkowalleck** [comment]
the report caused #294

**Comment by Ripolin** [comment]
> @Ripolin,
> 
> Which version of yarn are you using? output of `yarn -v` Which versions of `@cyclonedx/bom` were you using? Which versions of `synp` were you using?
> 
> Which packages were you using? output of `yarn list`? Could you provide a reproducible example? maybe as a pull-request? or as a standalone repository?
> 
> please see the reproducible example here: https://github.com/CycloneDX/cyclonedx-node-module/tree/master/tests/integration/with-yarn1-lockfile

My version of Yarn is 3.2.0 and I try version 3.7 and 3.8 of `@cyclonedx/bom`.

My  ```yarn.lock``` file format is yaml used by Yarn v2 berry and not the legacy one from Yarn v1.

**Comment by mpedro12** [comment]
> Hi,
> 
> For which version of Yarn this feature works ? Because when using on yarn v2 I've got the error `SyntaxError: Unknown token: { line: 3, col: 2, type: 'INVALID', value: undefined } 3:2 in lockfile`.

Any solution to this ? Getting the same error, using yarn3

**Comment by jkowalleck** [comment]
no solution yet.
followup is https://github.com/CycloneDX/cyclonedx-node-module/issues/294
