### ISSUE TITLE
Include `component.author` node in generated SBOM

### ISSUE THREAD

**Issue by shiraze** [CycloneDX/cyclonedx-node-module#246]
I noticed that the `author` node from the `package.json` file isn't included in the generated SBOM. I would expect this value to be copied to the SBOM `metadata.component.author` node.

**Comment by jkowalleck** [comment]
thaks for the hint, @shiraze 
could you review #247?

**Comment by shiraze** [comment]
I think code should follow existing pattern, so:
```
this._author = (pkg.author?.name) ? pkg.author.name : undefined
```

And the expectation is that `package.json` would contain set
```
...
 "author": { "name": "a name" },
...
```

Having said that, though, your code change would also be correct, but wouldn't it be better to use the "private" _author field?
