### ISSUE TITLE
spec 1.4: `component.version` optional

### ISSUE THREAD

**Issue by jkowalleck** [CycloneDX/cyclonedx-node-module#249]
from spec 1.4 on the Component's `version` is no longer required.
therefore it may be undefined and can be omitted when normalizing to JSON or to XML.
an empty version string is still valid.

feature: 
make `version` optional in setters.
make `version` default to `undefined`

**Comment by vanthome** [comment]
when will spec 1.4 be supported? It's already supported by the npm flavour of this module as it seems.

**Comment by jkowalleck** [comment]
there is no CDX 1.4 support in this package. nobody implemented it, yet. 

it has not been decided how the future of this package will look like. 
i suggested to the board a plan as described here: https://github.com/CycloneDX/cyclonedx-node-module/pull/321
