### ISSUE TITLE
Improve hash support

### ISSUE THREAD

**Issue by stevespringett** [CycloneDX/cyclonedx-node-module#25]
Hash support needs serious improvement. It appears that hashes are derived from the package itself, rather than calculating them. If the package didn't have a hash, it doesn't show up in the resulting bom. In addition, if a components package does have a hash, its rare that it will contain more than one (sha1, sha-512, but not both for example).

Need to investigate the ability to generate all supported hashes for packages and ensure that unmodified packages have the same hash value as stated in the package manifest. If a hash is generated that doesn't match what's in the package, then flip the `modified` element to true.

**Comment by jkowalleck** [comment]
this feature was implemented in the NPM flavour of this package: 
https://github.com/CycloneDX/cyclonedx-node-npm/
