### ISSUE TITLE
3.4.0 - ReferenceError: Name is required

### ISSUE THREAD

**Issue by IonKiwi** [CycloneDX/cyclonedx-node-module#252]
Upgraded from 3.3.1 to 3.4.0.
Running 3.4 results in the following error:

C:\Tools\node\node_modules\@cyclonedx\bom\model\CycloneDXObject.js:35
      if (required) { throw new ReferenceError(name + ' is required') }
                      ^

ReferenceError: Name is required
    at Component.validateType (C:\Tools\node\node_modules\@cyclonedx\bom\model\CycloneDXObject.js:35:29)
    at Component.set name [as name] (C:\Tools\node\node_modules\@cyclonedx\bom\model\Component.js:276:23)
    at new Component (C:\Tools\node\node_modules\@cyclonedx\bom\model\Component.js:98:17)
    at Bom.createMetadata (C:\Tools\node\node_modules\@cyclonedx\bom\model\Bom.js:48:26)
    at new Bom (C:\Tools\node\node_modules\@cyclonedx\bom\model\Bom.js:39:29)
    at C:\Tools\node\node_modules\@cyclonedx\bom\index.js:33:15
    at C:\Tools\node\node_modules\read-installed\read-installed.js:142:5
    at C:\Tools\node\node_modules\read-installed\read-installed.js:263:14
    at cb (C:\Tools\node\node_modules\slide\lib\async-map.js:47:24)
    at C:\Tools\node\node_modules\read-installed\read-installed.js:263:14

OS: Windows Server 2019
NodeJS: 16.5.0
Command: cyclonedx-bom -o bom.js

**Comment by jkowalleck** [comment]
@IonKiwi please provide more details: 
* the npm-lockfile  that was used (upload/atack it to the issue)

**Comment by IonKiwi** [comment]
attached the lock file that was used
[package-lock.zip](https://github.com/CycloneDX/cyclonedx-node-module/files/8042555/package-lock.zip)

**Comment by IonKiwi** [comment]
Also attached the package.json file.
[package.zip](https://github.com/CycloneDX/cyclonedx-node-module/files/8042638/package.zip)

Steps to reproduce:
npm install -g @cyclonedx/bom
npm install (in the directory with the attached package.json)
cyclonedx-bom -o bom.js

with 3.3.1 that results in the sbom file, with 3.4.0 it results in the above error

**Comment by jkowalleck** [comment]
thanks for the report @IonKiwi .

I am working on a fix.

**Comment by jkowalleck** [comment]
fix was implemented. #253 
ready for review&merge&release

**Comment by jkowalleck** [comment]
@IonKiwi a fix was released via 3.4.1
could you check?

**Comment by IonKiwi** [comment]
Great! can confirm that it's fixed
