### ISSUE TITLE
Differences in bom.xml depending on the platform (Windows vs. Linux)

### ISSUE THREAD

**Issue by CompartMSL** [CycloneDX/cyclonedx-node-module#26]
npm 6.4.1
node v10.15.3
@cyclonedx/bom 1.0.2 

The generated xml output differs, if you generate it on Windows or on Linux. Actually with Linux you get less components with license texts. The license texts of the components is missing, if their license file has only a lowercase file name.

E.g. on Linux:
 - License file of package glob@7.1.4 is captured, because the filename is "LICENSE"
 - License file of package path-is-absolute@1.0.1 is not captured, because the filename is "license"

**Comment by CompartMSL** [comment]
I was not able to create a branch. So I propose following fix in file index.js near line 40 by this way:
-    let licenseFilenames = [ 'LICENSE', 'LICENCE', 'License', 'Licence', 'NOTICE', 'Notice' ];
+    let licenseFilenames = [ 'LICENSE', 'License', 'license', 'LICENCE', 'Licence', 'licence', 'NOTICE', 'Notice', 'notice' ];

**Comment by stevespringett** [comment]
Thanks for reporting the issue and suggesting a fix. v1.0.4 in npmjs is available with this fix.

**Comment by CompartMSL** [comment]
Thanks for the fast 1.0.4
