### ISSUE TITLE
Question: Does it suffice to run npm install instead of ng build in order to generate the BOM for an Angular project? 

### ISSUE THREAD

**Issue by mrtnbm** [CycloneDX/cyclonedx-node-module#301]
Question: 1. Is it enough to run an "npm install" in the root directory of the Angular project to then generate the BOM or should the complete project be built with the configured angular.json? Otherwise, are certain dependencies missing from the BOM?
2. What is the difference between the cyclonedx-node-module and the cyclonedx-webpack-plugin, don't they both contain the same features?

**Comment by stevespringett** [comment]
npm install followed by bom creation should be enough.

Webpack tree-shakes resulting in unused dependencies being excluded and only the functions that are used being included as part of a bundle. If you only want to include dependencies that are actually shipped with a web frontend, then the webpack plugin would be the way to go.

**Comment by mrtnbm** [comment]
Ok, thank you for the explanation.
