### ISSUE TITLE
Exception if #purl is not available

### ISSUE THREAD

**Issue by peschuster** [CycloneDX/cyclonedx-node-module#308]
When a component has no "#purl" (e.g. no version is set), the following line raises an exception:
https://github.com/CycloneDX/cyclonedx-node-module/blob/7ea9cb55d35767593f70a1b24e2b956c777aa94d/model/Component.js#L522

I'd suggest using `&&` rather than `||` to fallback to other properties of the module for comparison, if one or the other component has no purl.

**Comment by jkowalleck** [comment]
PullRequests are welcome

**Comment by peschuster** [comment]
The packageUrl spec states that the version is optional, but the component model creates the packageUrl only when a version is specified.
Creating purl also when no version is given changes the behavior of the component class. Is this fine or would you prefer to keep the current behavior?

**Comment by jkowalleck** [comment]
would be fine.

**Comment by jkowalleck** [comment]
@peschuster are you planning to open a pull request, or should the topic be flagged as "help wanted" ?

**Comment by peschuster** [comment]
I am not sure about the approach, yet. Building a purl also when no version is set leads to a lot of failing tests.
My latest version just fixes the raised exception. So I will probably create a PR from that.
