### ISSUE TITLE
cyclonedx-node-module ignores package-lock.json

### ISSUE THREAD

**Issue by oxdef** [CycloneDX/cyclonedx-node-module#32]
To get list of installed components `cyclonedx-node-module` uses module `read-installed`. Which read this information from `package.json` and `node_modules` (see https://github.com/npm/read-installed/blob/master/read-installed.js). So we need either update docs for usage of `cyclonedx-node-module` and add required base step `npm install` before launching of `cyclonedx-bom` . Or implement support for `package-lock.json`...Without this step `cyclonedx-bom` generates empty BOM file for project with `package.json` and `package-lock.json` but without `node_modules`.

**Comment by stevespringett** [comment]
The lock file doesn't provide enough information so it cannot be used by itself. node_modules needs to be there.

I'm in the process of completely refactoring the node module. I'll add a check that outputs some help in the event a BOM with zero components is produced. Look for these changes in v2.0.0 of the module.

**Comment by stevespringett** [comment]
This has been incorporated into v2.0.0 and will be available soon.

**Comment by agar23** [comment]
@stevespringett curious what information you get from `node_modules` that you cant see in `package-lock.json` ? 

requiring `node_modules` adds extra steps (and time) when doing this on the CI.

**Comment by stevespringett** [comment]
The following data can easily be incorporated into a BOM using node_modules, but not with a package-lock.json:

* Component description
* Component type (framework, library, etc)
* Authors
* License
* License file
* Website URL
* Issue tracker URL
* VCS URL

SPDX license ID and optional license file are obviously valuable for legal and compliance use cases. The URLs are valuable not only for documentation purposes, but for advanced forms of analysis as well (e.g. project health). In addition, future versions of the node plugin will include every file-level component and their corresponding hash values, etc, that provided integrity above and beyond what package-lock.json is capable of achieving.
