### ISSUE TITLE
Generated POM is empty

### ISSUE THREAD

**Issue by nille** [CycloneDX/cyclonedx-node-module#33]
I'm running cyclonedx-bom v. 1.0.4 and want to test and generate a POM from the Vue.js repo (https://github.com/vuejs/vue). I have cloned the repo locally and cd:d to that directory:

`cyclonedx-bom`
Result:
```
<?xml version="1.0" encoding="UTF-8"?>
<bom xmlns="http://cyclonedx.org/schema/bom/1.1" version="1" serialNumber="urn:uuid:87c904d4-7d21-4f51-aef2-8aaa7496a556">
    <components>
    </components>
</bom>
```
The I try to run `npm install`which results in:
```
added 1491 packages from 1554 contributors and audited 11951 packages in 36.94s
found 14 vulnerabilities (3 low, 10 high, 1 critical)
  run `npm audit fix` to fix them, or `npm audit` for details
```
Once again I try `cyclonedx-bom`:
```
<?xml version="1.0" encoding="UTF-8"?>
<bom xmlns="http://cyclonedx.org/schema/bom/1.1" version="1" serialNumber="urn:uuid:85ab67e4-1942-4f07-abd4-3b8d5ed2ef3c">
    <components>
    </components>
</bom>
```

What am I doing wrong here? Seems to me the output should not be an empty XML file?

**Comment by vaaralav** [comment]
Vue.js project seems to have only `devDependencies`. They're not included in SBoM by default. If you want them included in SBoM, use `cyclonedx-bom -d`. Check `cyclonedx-bom -h` to see all available flags.

**Comment by nille** [comment]
Ah, I see. Thanks! The -d switch did the trick.

**Comment by stevespringett** [comment]
Closing.
