### ISSUE TITLE
There are no components in the bom

### ISSUE THREAD

**Issue by Stidgit** [CycloneDX/cyclonedx-node-module#336]
Im getting a problem while attempting to create an sbom. It is as follow: "There are no components in the BOM. The project may not contain dependencies or node_modules does not exist. Executing `npm install` prior to CycloneDX may solve the issue."

<img width="749" alt="image" src="https://user-images.githubusercontent.com/111974729/195601356-f94ffd9d-2562-4137-b93d-48a03d11e45e.png">
I have both node_module and package.json

Im running "cyclonedx-node --output bom.json" and Ive read that you need to add "--include-dev", but I dont want the devDependencies, I need the normal dependencies which are in the package.json

**Comment by Stidgit** [comment]
This problem is outside of root directory

**Comment by jkowalleck** [comment]
Could you provide a reproducible example? 
upload your whole project or the relent parts somewhere, having a dedicated repo on github is preferred. 

anyways, there is probably no cure. If your project is NPM based, then you could try https://www.npmjs.com/package/%40cyclonedx/cyclonedx-npm and let me know if it helped.

**Comment by Stidgit** [comment]
> Could you provide a reproducible example? upload your whole project or the relent parts somewhere, having a dedicated repo on github is preferred.
> 
> anyways, there is probably no cure. If your project is NPM based, then you could try https://www.npmjs.com/package/%40cyclonedx/cyclonedx-npm and let me know if it helped.

If I want to sbom a specific directory in a project with cyclonedx-npm, it complains about the package lock file or shrinkwrap file missing. What could I do about this?

**Comment by jkowalleck** [comment]
again, please: 
> Could you provide a reproducible example? upload your whole project or the relent parts somewhere, having a dedicated repo on github is preferred.

**Comment by Stidgit** [comment]
> again, please:
> 
> > Could you provide a reproducible example? upload your whole project or the relent parts somewhere, having a dedicated repo on github is preferred.

I'll make a minimized version of this repo and inform you later. I don't have the time right now.

**Comment by jkowalleck** [comment]
this issue got closed due to #321
