### ISSUE TITLE
Adding maven generated BOM breaks xml

### ISSUE THREAD

**Issue by relnah** [CycloneDX/cyclonedx-node-module#34]
When generating node BOM and using -a to add an already generated maven-project BOM (1.5.0+) the xml is broken since the maven BOM, since version 1.5.x has dg: namespace defined. Node generated BOM has not.

This scenario is very useful for us since we deliver Java-backend and JS frontend in same package but they are build with their respective build tools.

**Comment by stevespringett** [comment]
As a temporary workaround you can use the previous version of the Maven plugin or you can disable the dependency graph option with the current version of the Maven plugin by setting `includeDependencyGraph` to false.

**Comment by relnah** [comment]
Thanks for quick response! Settings back to 1.4.1 worked as a temporary fix. Roighly when do you think a fix might be released?

Best holiday whishes!

**Comment by stevespringett** [comment]
Fixed in v1.1.2. Note, schema extensions are not supported and will be a future enhancement.
