### ISSUE TITLE
Missing feature in Version 4 / cyclonedx-npm to inlcuse License text

### ISSUE THREAD

**Issue by vanthome** [CycloneDX/cyclonedx-node-module#343]
Hi, since version 4 (which seems to have dropped the executable completely) I cannot generate a BoM that contains the license text. In version 3 of this package it was possible. I tried to switch to @cyclonedx/cyclonedx-npm but lacks this feature. Can you give any indication how to deal with this?
BG

**Comment by jkowalleck** [comment]
Thanks for the feedback, @vanthome.

> I tried to switch to @cyclonedx/cyclonedx-npm but lacks this feature.

if you want to request a feature, please open a request in the dedicated ecosystem implementation, in your case it is <https://github.com/CycloneDX/cyclonedx-node-npm>.

> In version 3 of this package it was possible.

This project's ReadMe and change log state:
>> Previous versions of this very package are still available via [npmjs versions](https://www.npmjs.com/package/@cyclonedx/bom?activeTab=versions) and [github releases](https://github.com/CycloneDX/cyclonedx-node-module/releases).

This means you could stay with version 3, until you are ready to migrate to an ecosystem-specific tool.

A friendly reminder: 
 The latest major version `4` release of [@cyclonedx/bom](https://www.npmjs.com/package/@cyclonedx/bom) introduced breaking changes.
 If you need the previous versions, be advised to pin your processes to the major version properly - install ala `npm i @cyclonedx/bom@^3`  or run ala `npx @cyclonedx/bom@^3`  (see the `@`  followed by a [version constraint](https://docs.npmjs.com/about-semantic-versioning) at the end?)

**Comment by jkowalleck** [comment]
the missing feature was requested via https://github.com/CycloneDX/cyclonedx-node-npm/issues/256

All questions were answered.
An downgrade path was described. 

I consider this topic as closed. 
If further discussion is needed, then let me know and i will convert this "Issue" to a "discussion"

**Comment by jkowalleck** [comment]
related to #404
