### ISSUE TITLE
"cyclonedx-bom: command not found" when installing cyclonedx-bom@4.0.2

### ISSUE THREAD

**Issue by EvgeniaPatsoni** [CycloneDX/cyclonedx-node-module#344]
Hello,

Up until now, in order to generate a bom.xml file for angular projects we used to execute the following commands inside the project directory, and the bom.xml file would be generated without any issues.:
- `npm install -g @cyclonedx/bom`
- `cyclonedx-bom -o bom.xml`

This seems to have stopped working as of versions >=4.0.0.

For example if v4.0.2 is installed, we receive the following error: `cyclonedx-bom: command not found` when we execute the `cyclonedx-bom` command. Upgrading our Node version does not seem to help either.

If we specify the version to 3.10.6: `npm install -g @cyclonedx/bom@3.10.6`, everything works as expected.

Is this a bug in the latest versions or are we missing something from our side?

We tried looking for any related documentation but did not find anything.

Thank you in advance.

**Comment by jkowalleck** [comment]
not a bug.
read https://github.com/CycloneDX/cyclonedx-node-module/releases/tag/v4.0.0

**Comment by EvgeniaPatsoni** [comment]
Dear @jkowalleck 

We have tried following the same procedure with `@cyclonedx/cyclonedx-npm` instead of `@cyclonedx/bom`, but as a result it spits out a whole lines of errors about several missing dependencies.

**Comment by jkowalleck** [comment]
feel free to read the documentation at https://github.com/CycloneDX/cyclonedx-node-npm 
and open [issues](https://github.com/CycloneDX/cyclonedx-node-npm/issues) and [discussions](https://github.com/CycloneDX/cyclonedx-node-npm/discussions) there.
