### ISSUE TITLE
SBOM can contain invalid URLs in externalReferences 

### ISSUE THREAD

**Issue by mmarseu** [CycloneDX/cyclonedx-node-module#352]
I'm seeing the same issue as #107 but the author doesn't seem to have followed up on it.

SBOM generated from package.json files using this tool sometimes contain illegal reference URLs. As opposed to #107, im using JSON notation. According to the JSON schema, the `components[].externalReferences[].url` field must be a valid _iri-reference_.  
In reality, authors of npm packages seem to put all kinds of repository URLs into their `package.json` files which aren't necessarily an _iri-reference_. 

In my Node.js application for which I'm creating an SBOM, I'm seeing the following pattern (`git@github.com:...`) a couple dozen times (among 1500 components):

```jsonc
{
   // For purl pkg:npm/%40aws-crypto/sha256-browser@2.0.0
    "externalReferences": [
        {
            "url": "git@github.com:aws/aws-sdk-js-crypto-helpers.git",
            "type": "vcs",
            "comment": "as detected from PackageJson property \"repository.url\""
        }
    ]
}
```

If I'm not misreading the [ANBF from RFC 3987](https://datatracker.ietf.org/doc/html/rfc3987#section-2.2), this isn't a valid IRI reference.

**Comment by jkowalleck** [comment]
Thanks for the report. I will check this. 

Anyway: this package no longer provides any own functionality, so you are reporting to the wrong place.
see https://github.com/CycloneDX/cyclonedx-node-module/issues/337

**Comment by jkowalleck** [comment]
out of scope of this package. please report to the correct project

**Comment by jkowalleck** [comment]
for future discussions: per https://json-schema.org/understanding-json-schema/reference/string.html 
the [RFC3987](https://tools.ietf.org/html/rfc3987) reflects foramt "iri-reference".

The ABNF for this is, according to <https://datatracker.ietf.org/doc/html/rfc3987#section-2.2>:
```ABNF
   IRI            = scheme ":" ihier-part [ "?" iquery ]
                         [ "#" ifragment ]

   ihier-part     = "//" iauthority ipath-abempty
                  / ipath-absolute
                  / ipath-rootless
                  / ipath-empty

   IRI-reference  = IRI / irelative-ref

   absolute-IRI   = scheme ":" ihier-part [ "?" iquery ]

   irelative-ref  = irelative-part [ "?" iquery ] [ "#" ifragment ]

   irelative-part = "//" iauthority ipath-abempty
                  / ipath-absolute
                  / ipath-noscheme
                  / ipath-empty

   iauthority     = [ iuserinfo "@" ] ihost [ ":" port ]
   iuserinfo      = *( iunreserved / pct-encoded / sub-delims / ":" )
   ihost          = IP-literal / IPv4address / ireg-name

   ireg-name      = *( iunreserved / pct-encoded / sub-delims )

   ipath          = ipath-abempty   ; begins with "/" or is empty
                  / ipath-absolute  ; begins with "/" but not "//"
                  / ipath-noscheme  ; begins with a non-colon segment
                  / ipath-rootless  ; begins with a segment
                  / ipath-empty     ; zero characters

   ipath-abempty  = *( "/" isegment )
   ipath-absolute = "/" [ isegment-nz *( "/" isegment ) ]
   ipath-noscheme = isegment-nz-nc *( "/" isegment )
   ipath-rootless = isegment-nz *( "/" isegment )
   ipath-empty    = 0<ipchar>

   isegment       = *ipchar
   isegment-nz    = 1*ipchar
   isegment-nz-nc = 1*( iunreserved / pct-encoded / sub-delims
                        / "@" )
                  ; non-zero-length segment without any colon ":"

   ipchar         = iunreserved / pct-encoded / sub-delims / ":"
                  / "@"

   iquery         = *( ipchar / iprivate / "/" / "?" )

   ifragment      = *( ipchar / "/" / "?" )

   iunreserved    = ALPHA / DIGIT / "-" / "." / "_" / "~" / ucschar

   ucschar        = %xA0-D7FF / %xF900-FDCF / %xFDF0-FFEF
                  / %x10000-1FFFD / %x20000-2FFFD / %x30000-3FFFD
                  / %x40000-4FFFD / %x50000-5FFFD / %x60000-6FFFD
                  / %x70000-7FFFD / %x80000-8FFFD / %x90000-9FFFD
                  / %xA0000-AFFFD / %xB0000-BFFFD / %xC0000-CFFFD
                  / %xD0000-DFFFD / %xE1000-EFFFD

   iprivate       = %xE000-F8FF / %xF0000-FFFFD / %x100000-10FFFD

   scheme         = ALPHA *( ALPHA / DIGIT / "+" / "-" / "." )

   port           = *DIGIT

   IP-literal     = "[" ( IPv6address / IPvFuture  ) "]"

   IPvFuture      = "v" 1*HEXDIG "." 1*( unreserved / sub-delims / ":" )

   IPv6address    =                            6( h16 ":" ) ls32
                  /                       "::" 5( h16 ":" ) ls32
                  / [               h16 ] "::" 4( h16 ":" ) ls32
                  / [ *1( h16 ":" ) h16 ] "::" 3( h16 ":" ) ls32
                  / [ *2( h16 ":" ) h16 ] "::" 2( h16 ":" ) ls32
                  / [ *3( h16 ":" ) h16 ] "::"    h16 ":"   ls32
                  / [ *4( h16 ":" ) h16 ] "::"              ls32
                  / [ *5( h16 ":" ) h16 ] "::"              h16
                  / [ *6( h16 ":" ) h16 ] "::"

   h16            = 1*4HEXDIG
   ls32           = ( h16 ":" h16 ) / IPv4address

   IPv4address    = dec-octet "." dec-octet "." dec-octet "." dec-octet

   dec-octet      = DIGIT                 ; 0-9
                  / %x31-39 DIGIT         ; 10-99
                  / "1" 2DIGIT            ; 100-199
                  / "2" %x30-34 DIGIT     ; 200-249
                  / "25" %x30-35          ; 250-255

   pct-encoded    = "%" HEXDIG HEXDIG

   unreserved     = ALPHA / DIGIT / "-" / "." / "_" / "~"
   reserved       = gen-delims / sub-delims
   gen-delims     = ":" / "/" / "?" / "#" / "[" / "]" / "@"
   sub-delims     = "!" / "$" / "&" / "'" / "(" / ")"
                  / "*" / "+" / "," / ";" / "="
```

**Comment by jkowalleck** [comment]
@mmarseu 

I dug some deeper, found that this issue might have existed in old versions of this package. versions <3.0 probably.


Version 3 is abandoned, in favor of version 4.
Version 4 no longer is a mix of library and several specific implementations, but a meta package.
Please upgrade to version 4, which should lead to a migration of the dedicated packages mentioned in the [README](https://github.com/CycloneDX/cyclonedx-node-module).

**Comment by mmarseu** [comment]
You are absolutely correct. I was using an old version of the the `@cyclonedx/cyclonedx-npm` package. The current version, installed through the meta-package, no longer produces this output.

So please disregard this issue. I apologize for the waste of time.

**Comment by jkowalleck** [comment]
> [...] So please disregard this issue. I apologize for the waste of time.I apologize for the waste of time.

no worries. it was not a waste of time at all.
I checked against the ABNF and you were correct, the mentioned string was inaccurate.

So I went over other projects I maintain and checked whether they had this kind of "url" normalized - which they had.
So in fact, your input made me check and assert other projects I maintain. :-)
