### ISSUE TITLE
Provide option to include/not include licenseText

### ISSUE THREAD

**Issue by mscudlik** [CycloneDX/cyclonedx-node-module#63]
As the lincenseText(s) can be quite long, it would be nice to have the option to include or not include the licenseText.

The maven module provides a similar option:

```xml
    <includeLicenseText>true</includeLicenseText>
```

**Comment by stevespringett** [comment]
By default, license text will not be included. There a command-line argument to include the full license text. This will be available once v2.0.0 is released.
