### ISSUE TITLE
Deprecation of Node.js 8 support

### ISSUE THREAD

**Issue by coderpatros** [CycloneDX/cyclonedx-node-module#82]
Official support of Node.js 8 ended last year. I'm proposing to drop support for it.

@stevespringett any concerns from you? It will mean another major version bump.

**Comment by stevespringett** [comment]
No objection from me. We already have a release that supports CycloneDX 1.2 and Node.js 8, so removing support for Node.js in the next major release seems perfectly reasonable.

**Comment by coderpatros** [comment]
Removed in v3.0.0
