### ISSUE TITLE
cyclonedx-bom -append not working as expected

### ISSUE THREAD

**Issue by siewer** [CycloneDX/cyclonedx-node-module#85]
I have a project with multiple packages on it. I would like to execute cyclonedx-bom on each package and append results to the root one but I am unable to do so.

steps to reproduce:
```
cd /tmp
git clone https://github.com/lerna/lerna
cd lerna
npm install
cyclonedx-bom
cat bom.xml | wc -l
> 37
cd utils/log-packed/
npm install
cyclonedx-bom -a /tmp/lerna/bom.xml
cat /tmp/lerna/bom.xml |wc -l
> 37
cat /tmp/lerna/utils/log-packed/bom.xml | wc -l
> 873
```

after running plugin in root directory I have bom of 37 lines (empty becouse root package.json does not contain any dependancies), after running cyclonedx-bom on another package (which has few dependencies) i get bom with 873 lines but setting -a to root bom did nothing, still 37 lines.

Can anyone give me a hint how to make it work?

**Comment by coderpatros** [comment]
Hi @siewer it works the other way around.

When you invoke `cyclonedx-bom -a /tmp/lerna/bom.xml` it is appending `/tmp/lerna/bom.xml` to the newly generated SBOM.

**Comment by siewer** [comment]
@coderpatros so the proper way to achieve my goal is to
1. Cd desired location
2. Npm install
3. Cyclonedx-bom 
4. Cd project root
5. Cyclonedx-npm -a desiredlocation/npm.xml 

And iterate through all packages?

**Comment by coderpatros** [comment]
That should do it.

Although a comma separated list should work for the last step too.

**Comment by stevespringett** [comment]
@siewer I'm curious why this approach is being taken. When generating BOMs, transitive dependencies will be included, so normally, there isn't a need to create BOMs for every package, unless of course that is the requirement.

**Comment by siewer** [comment]
@coderpatros thanks I will verify it in few hours!

@stevespringett I am not an expert in field of npm projects. It happen to me multiple times that I have encountered multi module project where running npm install && cyclonedx-bom in root directory produced me an empty bom while running cyclonedx-bom on separate modules provide results

**Comment by coderpatros** [comment]
For any future visitors to this issue. You shouldn't normally need this for a single Node.js project. But might need it for mono repos where you want to create a consolidated view for the entire repo.

Another really good use case is where you are generating an SBOM for server and client side dependencies. i.e. .NET for server side and JS client side.
