### ISSUE TITLE
Silently fails when specified output subdirectory doesn't exist

### ISSUE THREAD

**Issue by hak33m16** [CycloneDX/cyclonedx-node-module#87]
Version: 2.0.1
Node Version: 10.20.1
OS: macOS Mojave 10.14.6

When running cyclonedx-bom and specifying a custom output location, if the location specified doesn't exist, the bom file won't be created but the process will exit successfully with no indication of failure

Given that this library aims to support Node 8.x and onward, it'd probably make the most sense to return a non-zero exit code and provide some kind of error message in this case (since native support for auto-creation of subdirectories on fs.writeFile doesn't seem to exist until 10.12.0 and this seems to be the culprit: https://github.com/CycloneDX/cyclonedx-node-module/blob/master/bin/cyclonedx-bom#L82)

**Comment by coderpatros** [comment]
Thanks for the report @hak33m16

**Comment by coderpatros** [comment]
Fixed in the latest release.
