### ISSUE TITLE
There are no components in the BOM

### ISSUE THREAD

**Issue by vincedy** [CycloneDX/cyclonedx-node-module#88]
Hello guys
while I'm trying to execute cyclonedx-bom, I'm always getting this

"There are no components in the BOM. The project may not contain dependencies or node_modules does not exist. Executing `npm install` prior to CycloneDX may solve the issue."

![image](https://user-images.githubusercontent.com/56834982/97003726-27823d80-153c-11eb-98d0-fb73e2aa60f7.png)

This is the screenshot.. as you can see after executing npm install, I have the node_modules created, but the cycloneDx doesn't really recognize it.

Can you help me with that please?

Thanks a lot
Vince

**Comment by stevespringett** [comment]
1) Are there packages defined in the package.json (and package-lock.json)?
2) What version of npm are you using?

**Comment by yq9721** [comment]
I hve the same problem,my version of npm is 6.14.6 and node version is 12.18.4.When I delete package.json file,it can works,but it will contains all child dependencies.

**Comment by vincedy** [comment]
> 1. Are there packages defined in the package.json (and package-lock.json)?
> 2. What version of npm are you using?

1. I have packages defined in package.json and package-lock.json. If I delete package.json the command works and generate the bom.xml... is that the normal behavior? should I delete both package.json and package-lock.json?
2.  npm: '6.13.4'

**Comment by stevespringett** [comment]
And why would you want to delete package.json? Wouldn't that destroy the project?

Please post the package.json so I can reproduce.

**Comment by vincedy** [comment]
> And why would you want to delete package.json? Wouldn't that destroy the project?
> 
> Please post the package.json so I can reproduce.

Yes I believe is not good to delete it... but I was just wondering why without the package.json it seemd to produce something at least. I also attach what I manage to produce without package.json in case you want to have a look 
[bom.zip](https://github.com/CycloneDX/cyclonedx-node-module/files/5437581/bom.zip)

Here you are the package.json as well, thanks for your help

[package.zip](https://github.com/CycloneDX/cyclonedx-node-module/files/5437574/package.zip)

**Comment by coderpatros** [comment]
The only specified dependencies are development dependencies. To include them you need to use the `--include-dev` option.

**Comment by coderpatros** [comment]
As to the why, this is the behaviour of read-installed. Without the package.json file it doesn't know that they are development dependencies.

**Comment by vincedy** [comment]
> The only specified dependencies are development dependencies. To include them you need to use the `--include-dev` option.

Thanks, that worked out well for me... much appreciated, didn't see this option at all...

**Comment by stevespringett** [comment]
Glad its working. Closing.

**Comment by coderpatros** [comment]
@yq9721 if `--include-dev` doesn't resolve this for you too just open a new issue.
