### ISSUE TITLE
append json not working

### ISSUE THREAD

**Issue by TraceyOnim** [CycloneDX/cyclonedx-node-module#90]
## Steps to reproduce
I have created two projects(first_project and second_project) . I was trying  to append json output from `first_project`  to the current json output added to `second_project` using the following command `cyclonedx-bom -o ../second_bom.json -a ~/first_project/first_bom.json`

## Output
When I open `second_bom.json` output file I can only see components for `second_project`.

## Expected output
Expected to see components for `first_project` appended to `second_bom.json` file

**Comment by sigu** [comment]
Seems this is not yet supported for JSON outputs following the code at:


https://github.com/CycloneDX/cyclonedx-node-module/blob/master/bin/cyclonedx-bom#L78-L92

**Comment by stevespringett** [comment]
This should work fairly well on XML. I don't think JSON is supported at the moment.

Also note, that all utility functions (such as appending/merging BOMs) will be moved to the new [CycloneDX CLI](https://github.com/CycloneDX/cyclonedx-cli/). I'd recommend creating an enhancement request for the project.

**Comment by coderpatros** [comment]
This feature has been removed in v3.0.0
